### ISSUE TITLE
[BUG]: pathways changes title of footer navigation blocks

### ISSUE THREAD

**Issue by da5nsy** [the-turing-way/the-turing-way#4107]
### Description

Current deployment at `https://book.the-turing-way.org/communication/communication`:
![Screenshot showing two direction buttons which both have the word pathways as the top text](https://github.com/user-attachments/assets/5d087a47-5b4f-4bc8-a69a-7f682d896544)

local* without pathways:

![Screenshot showing two direction buttons which both have "The Turing Way" as the top text](https://github.com/user-attachments/assets/c803ef4f-16c1-427b-b1b6-4c9df0bdbf32)

### Your personal set up

\*
```console
python3.13 -m venv ./venv
source ./venv/bin/activate
python -m pip install --upgrade pip
pip install pip-tools
cd book
make deps
make serve
```

**Comment by JimMadge** [comment]
Seems to happen after wherever the Pathways item is placed in the ToC, not sure why.

**Comment by JimMadge** [comment]
Adding a `file` entry for the Pathways item seems to fix this. For example,

```yaml
  toc:
  - file: index.md
  - title: Pathways B
    file: pathways/pathways.md
    children:
    - pattern: pathways/*.md
```

instead of


```yaml
  toc:
  - file: index.md
  - title: Pathways B
    children:
    - pattern: pathways/*.md
```
