### ISSUE TITLE
Enable CORS on netlify for dynamic cross-references in MyST

### ISSUE THREAD

**Issue by rowanc1** [the-turing-way/the-turing-way#4150]
I am trying to do a myst cross-reference from my own research to the turing way, and to do that client-side JSON requests need to be enabled for CORS. Adding something like this to the `netlify.toml`:

```toml
[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*"
```

https://answers.netlify.com/t/support-guide-handling-cors-on-netlify/107739#h-321-for-static-assets-6

I don't think there is a downside to enabling this on static assets, and it enables the JSON to be read and linked to from other myst sites.

To reproduce in a small myst site: `myst.yml`:

```yaml
project:
  references:
    tw: https://book.the-turing-way.org
```

`index.md`:

```
This is sometimes referred to as the [research compendium](xref:tw/reproducible-research/compendia#summary).
```
