### ISSUE TITLE
[BUG]: 'Edit' button on website does not redirect to main brain of project on Github

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#4246]
### Description

Pressing the 'edit' button on the website doesn't take the user to the main brain.

<img width="762" alt="Image" src="https://github.com/user-attachments/assets/7f2a58cf-521f-4e19-b532-89d30ac13e59" />

After clicking on this button, the user is redirected to a new page:

<img width="1784" alt="Image" src="https://github.com/user-attachments/assets/5a4ed557-0382-4dd1-814e-493db3262806" />

### Your personal set up

- **Operating System**:
- **Browser**:

**Comment by SakshamSharma10989** [comment]
Hi! I’m interested in this issue. Can I work on it?

**Comment by JimMadge** [comment]
@SakshamSharma10989 Absolutely :tada:

**Comment by SakshamSharma10989** [comment]
Hi, I got assigned to this but can’t work on it right now. Please feel free to reassign it. Sorry!

**Comment by bsipocz** [comment]
I would say this is an upstream bug as it's unlikely to have any easy-to-implement workaround for it in the TTW repo.
(also, https://github.com/jupyter-book/mystmd/pull/2138 may have already fixed it).

An easy first issue part would be to open this same bug report upstream, in the mystmd repo.

**Comment by bsipocz** [comment]
> The [MyST Markdown docs](https://mystmd.org/guide/) always seem to redirect to the main branch for example.

As Jim said above, the fact that this issuee doesn't come up upstream means that at minimum this should be a missing documentation issue for upstream, but likely a bugfix somewhere in the theme or the main repo.

**Comment by kafitzgerald** [comment]
Just noting that issue is limited to TTW deployed version and deploy previews in case that's helpful in troubleshooting and seems to relate to how mystmd is interpreting the branch for those.  The relevant code for that is here: https://github.com/jupyter-book/mystmd/blob/main/packages/myst-cli/src/utils/addEditUrl.ts#L23

I'm not familiar enough with how this book is deployed to know if this might be an issue here or upstream though.

**Comment by JimMadge** [comment]
Ah, disappointing it wasn't just about our configuration. I'm not sure what the issue is then but opening a bug report upstream seems like the next move. Has anyone opened one?

**Comment by bsipocz** [comment]
I haven't checked. It's really confusing that the mystmd docs works as expected, I don't see anything extra in their config that trivially stands out.

**Comment by bsipocz** [comment]
I've reported this upstream: https://github.com/jupyter-book/mystmd/issues/2234

**Comment by bbartholdy** [comment]
Since this is still an issue (for me the button leads to a 404 error), maybe it's best to disable the button temporarily?

As far as I can tell it would be in the *myst.yml* file at the bottom:

```yml
site:
  options:
    logo: ../figures/logo-detail-with-text.svg
    favicon: ../figures/logo/favicon-32x32.png
    analytics_google: UA-167881009-1
    folders: true
    edit_url: null # new line
  template: book-theme
```

**Comment by bsipocz** [comment]
👍 for disabling this for now. 
(That said, I still don't see why it's not working here, I don't have this issue in any of my JB2 other repos)

**Comment by bsipocz** [comment]
(The one big difference I see between those repos and TTW is that I always have the `myst.yaml` config in the root of the repo rather than deep in a sub-directory)

**Comment by bbartholdy** [comment]
If I add `edit_url: null`, nothing happens. According to the documentation the frontmatter should be added to `project:`

Does not work:

```yml
project:
  title: The Turing Way
  authors:
    - name: The Turing Way Community
  copyright: 2019-2025
  exclude:
    - LICENSE.md
  github: the-turing-way/the-turing-way
  edit_url: null
. . .
```
